"""Model card generation.

A model card is not documentation you write at the end — it is an artifact the
pipeline emits, so it cannot drift from the model it describes. Every number in
here comes from the evaluation report; nothing is typed by hand.

The sections follow the structure the Hugging Face Hub expects (and that the
Model Cards paper proposed): what it is, how it was made, how it scored, and —
the section most people skip and the one that matters most — what it should not
be used for.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:  # pragma: no cover
    from forgeml.config import ForgeConfig
    from forgeml.data.versioning import DatasetFingerprint
    from forgeml.evaluation.evaluator import EvaluationReport
    from forgeml.optimization.selector import SelectionResult


def build_model_card(
    config: ForgeConfig,
    report: EvaluationReport,
    selection: SelectionResult | None = None,
    fingerprint: DatasetFingerprint | None = None,
    registered_version: str | None = None,
) -> str:
    """Render the full model card as Markdown."""
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    quality = report.quality.scores

    sections: list[str] = [
        f"# {config.tracking.registered_model_name}",
        "",
        "> Generated by the ForgeML pipeline. Every number below is read from the "
        "evaluation artifacts of the run that produced this model — none of it is "
        "written by hand.",
        "",
        f"*Generated {generated}*",
        "",
        "## Overview",
        "",
        f"- **Base model**: `{config.model.name}`",
        f"- **Fine-tuning method**: {config.training.method.upper()}",
        f"- **Dataset**: `{config.data.source}` (version `{config.data.version}`)",
        f"- **Registered version**: {registered_version or 'not registered'}",
        f"- **Max sequence length**: {config.model.max_seq_length} tokens",
    ]

    if config.quantization.enabled:
        sections.append(
            f"- **Quantization**: {config.quantization.bits}-bit "
            f"{config.quantization.quant_type.upper()} "
            f"(double quant: {config.quantization.double_quant})"
        )
    if config.lora is not None:
        sections.append(
            f"- **LoRA**: r={config.lora.r}, alpha={config.lora.alpha} "
            f"(scaling {config.lora.scaling:.1f}), dropout={config.lora.dropout}"
        )
        if config.lora.target_modules:
            sections.append(f"- **Target modules**: `{', '.join(config.lora.target_modules)}`")

    # -- results -----------------------------------------------------------
    sections += [
        "",
        "## Evaluation",
        "",
        f"Measured on {report.num_eval_examples} held-out test examples with greedy decoding.",
        "",
        "| Metric | Value |",
        "|---|---:|",
    ]

    for name, value in quality.items():
        sections.append(f"| {name} | {value:.4f} |")
    if report.perplexity:
        sections.append(f"| perplexity | {report.perplexity.perplexity:.3f} |")
    if report.latency:
        sections += [
            f"| latency mean | {report.latency.mean_ms:.1f} ms |",
            f"| latency p95 | {report.latency.p95_ms:.1f} ms |",
            f"| throughput | {report.latency.tokens_per_second:.1f} tok/s |",
        ]
    if report.memory:
        sections += [
            f"| peak memory | {report.memory.peak_allocated_mb:.0f} MB |",
            f"| weights | {report.memory.weights_mb:.0f} MB |",
        ]
    sections.append(f"| model size | {report.model_size_mb:.0f} MB |")
    if report.cost:
        sections.append(
            f"| est. cost / 1k requests | ${report.cost.cost_per_1k_requests_usd:.4f} |"
        )

    # -- selection ---------------------------------------------------------
    if selection is not None and selection.champion is not None:
        sections += [
            "",
            "## Why this model was selected",
            "",
            "Selection was automatic. Candidates were filtered against hard "
            "constraints, every metric was normalised across the candidate set, "
            "and the winner maximised a weighted utility:",
            "",
            "```",
            *[f"{k:<12} {v}" for k, v in selection.weights.items()],
            "```",
            "",
            selection.to_markdown(),
        ]
        gain = selection.quality_gain_vs_baseline()
        speedup = selection.speedup_vs_baseline()
        if gain is not None or speedup is not None:
            sections += ["", "**Versus the untuned baseline:**", ""]
            if gain is not None:
                sections.append(f"- quality {gain:+.4f}")
            if speedup is not None:
                sections.append(f"- latency {speedup:.2f}x")

    # -- training config ---------------------------------------------------
    sections += [
        "",
        "## Training configuration",
        "",
        "```yaml",
        f"method:                {config.training.method}",
        f"epochs:                {config.training.epochs}",
        f"learning_rate:         {config.training.learning_rate}",
        f"effective_batch_size:  {config.training.effective_batch_size}",
        f"lr_scheduler:          {config.training.lr_scheduler_type}",
        f"warmup_ratio:          {config.training.warmup_ratio}",
        f"weight_decay:          {config.training.weight_decay}",
        f"gradient_checkpointing:{config.training.gradient_checkpointing}",
        f"optimizer:             {config.training.optim}",
        f"seed:                  {config.training.seed}",
        "```",
    ]

    # -- data --------------------------------------------------------------
    if fingerprint is not None:
        sections += [
            "",
            "## Dataset",
            "",
            f"- **Source**: `{fingerprint.source}`",
            f"- **Version**: `{fingerprint.version}`",
            f"- **Examples**: {fingerprint.num_examples:,}",
            f"- **Content hash**: `{fingerprint.content_hash[:32]}`",
        ]
        if fingerprint.split_sizes:
            splits = ", ".join(f"{k} {v:,}" for k, v in fingerprint.split_sizes.items())
            sections.append(f"- **Splits**: {splits}")
        sections += [
            "",
            "The content hash covers every example. Re-running the data pipeline and "
            "recomputing it is how you verify this model was trained on the data "
            "this card claims.",
        ]

    # -- the honest sections -----------------------------------------------
    sections += [
        "",
        "## Intended use",
        "",
        "- Short-form instruction following in English, in the style of the training corpus.",
        "- Demonstrating and benchmarking parameter-efficient fine-tuning trade-offs.",
        "",
        "## Out of scope",
        "",
        "- **Factual lookup.** A model of this size hallucinates confidently. "
        "Nothing it outputs should be trusted without verification.",
        "- **Medical, legal, or financial advice.**",
        "- **Any decision affecting a person** — hiring, credit, moderation, safety.",
        "- **Languages other than English**, which the training data barely covers.",
        "",
        "## Limitations",
        "",
        "- **The quality metrics measure n-gram overlap with a single reference "
        "answer.** A correct paraphrase scores badly; a fluent falsehood scores "
        "well. Read `evaluation/samples.md` in the run artifacts before trusting "
        "the aggregate number.",
        f"- **Evaluated on {report.num_eval_examples} examples**, which is enough "
        "to rank candidates against each other and too few to state an absolute "
        "capability.",
        "- **Latency and memory are hardware-specific.** They were measured on "
        f"the environment recorded in the run's `env.*` tags, assuming "
        f"{config.evaluation.assumed_gpu}. Different hardware, different numbers.",
        "- **Cost is a derived estimate**, computed from measured throughput and a "
        f"stated rate of ${config.evaluation.gpu_hourly_usd:.2f}/hour. It ignores "
        "cold starts, idle time and autoscaling headroom, so treat it as a "
        "relative ranking signal rather than a budget.",
        "- **Inherited bias.** Fine-tuning does not remove what the base model "
        "learned during pretraining.",
        "",
        "## Reproducing this model",
        "",
        "```bash",
        f"forgeml train --config configs/{config.training.method}.yaml",
        "```",
        "",
        "The exact resolved configuration is attached to the MLflow run as "
        "`config/resolved_config.yaml`, and the code commit is recorded in the "
        "`env.git_commit` tag.",
        "",
    ]

    return "\n".join(sections)


def write_model_card(
    path: str | Path,
    config: ForgeConfig,
    report: EvaluationReport,
    selection: SelectionResult | None = None,
    fingerprint: DatasetFingerprint | None = None,
    registered_version: str | None = None,
) -> Path:
    """Render and write the card to disk."""
    card = build_model_card(config, report, selection, fingerprint, registered_version)
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(card, encoding="utf-8")
    return target


def build_results_table(candidates: list[Any]) -> str:
    """Standalone experiment comparison table for `docs/experiments.md`."""
    header = (
        "| Run | Method | Quality | Latency p95 | Peak memory | Size | Cost/1k |\n"
        "|---|---|---:|---:|---:|---:|---:|"
    )
    rows = [
        f"| {c.run_name} | {c.method} | {c.quality:.4f} | {c.latency_ms:.0f} ms | "
        f"{c.memory_mb:.0f} MB | {c.model_size_mb:.0f} MB | ${c.cost_per_1k_usd:.4f} |"
        for c in candidates
    ]
    return "\n".join([header, *rows])
